#!/usr/bin/env python3
"""setup_mcp.py — generate the machine-local `opencode.jsonc` MCP configuration.

OpenCode resolves a *relative* MCP `cwd` against the **session directory**, not
against the config file or the git root. A repo-relative `cwd` therefore works
only while you happen to sit at the repository root and breaks as soon as a
session is rooted anywhere else (`papers/<slug>/`, a legacy folder, a subagent
directory):

    NotFound: FileSystem.access (D:\\...\\papers\\c20-2026\\.agents\\skills\\...)

The academic-search server does not need a `cwd` at all: it imports
`sources`/`utils` as plain top-level modules (Python puts the script's own
directory on `sys.path[0]`) and loads `config.toml` through `Path(__file__)`.
So this script drops `cwd` entirely and writes an **absolute script path**
resolved from the repository root. That works from any subdirectory, on any
platform, on any machine.

`opencode.jsonc` holds an absolute path, so it is machine-local and gitignored;
`opencode.jsonc.example` is the committed template. Every clone runs this once:

    python scripts/setup_mcp.py

Servers already present in `opencode.jsonc` (for example `gdrive`) are
preserved: this script only owns the entries declared in the example.

Usage:
    python scripts/setup_mcp.py            # write/refresh opencode.jsonc
    python scripts/setup_mcp.py --check    # verify only; exit 1 if stale/missing
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _repo import find_repo_root  # noqa: E402

REPO_ROOT_TOKEN = "__REPO_ROOT__"
CONFIG_NAME = "opencode.jsonc"
EXAMPLE_NAME = "opencode.jsonc.example"

HEADER = """// opencode.jsonc — GENERATED by scripts/setup_mcp.py. Do not edit by hand.
//
// This file is machine-local and gitignored because it contains an absolute
// path to the MCP server. To change which servers are configured, edit
// opencode.jsonc.example and re-run:  python scripts/setup_mcp.py
//
// Any MCP server you add by hand is preserved across runs.
"""


def strip_jsonc(text: str) -> str:
    """Remove `//` and block comments and trailing commas, respecting strings."""
    out: list[str] = []
    i, n = 0, len(text)
    in_string = False
    quote = ""
    while i < n:
        ch = text[i]
        if in_string:
            out.append(ch)
            if ch == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                in_string = False
            i += 1
            continue
        if ch in "\"'":
            in_string = True
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(ch)
        i += 1
    return re.sub(r",(\s*[}\]])", r"\1", "".join(out))


def load_jsonc(path: Path) -> dict:
    """Read a JSONC file into a dict; return {} when absent or unreadable."""
    if not path.is_file():
        return {}
    data = json.loads(strip_jsonc(path.read_text(encoding="utf-8")))
    return data if isinstance(data, dict) else {}


def expected_script(repo: Path) -> Path:
    return repo / ".agents" / "skills" / "paper-search" / "mcp-server" / "academic_search_server.py"


def current_script_path(config: dict) -> str | None:
    """Extract the configured server script path from an opencode.jsonc mapping."""
    servers = config.get("mcp")
    if not isinstance(servers, dict):
        return None
    # Tolerate both the flat and the nested `mcp.servers` shapes.
    if isinstance(servers.get("servers"), dict):
        servers = servers["servers"]
    entry = servers.get("academic-search")
    if not isinstance(entry, dict):
        return None
    for arg in entry.get("command", []):
        if str(arg).endswith("academic_search_server.py"):
            return str(arg)
    return None


def build_config(repo: Path, example: dict, existing: dict) -> dict:
    """Generated example (paths resolved) + any hand-added servers/keys from existing."""
    resolved = json.loads(json.dumps(example).replace(REPO_ROOT_TOKEN, repo.as_posix()))
    out: dict = {k: v for k, v in resolved.items() if k != "mcp"}
    merged: dict = dict(resolved.get("mcp") or {})

    for key, value in (existing or {}).items():
        if key != "mcp":
            out[key] = value
            continue
        servers = value
        if isinstance(servers, dict) and isinstance(servers.get("servers"), dict):
            servers = servers["servers"]
        if isinstance(servers, dict):
            for name, cfg in servers.items():
                merged.setdefault(name, cfg)

    out["mcp"] = merged
    # $schema first, for readability.
    ordered = {"$schema": out.pop("$schema")} if "$schema" in out else {}
    ordered.update(out)
    return ordered


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate the machine-local opencode.jsonc MCP configuration."
    )
    ap.add_argument("--root", default=None, help="repository root (auto-detected)")
    ap.add_argument("--check", action="store_true",
                    help="report a missing/stale opencode.jsonc and exit 1 without changing anything")
    args = ap.parse_args()

    repo = Path(args.root).resolve() if args.root else find_repo_root()
    example_path = repo / EXAMPLE_NAME
    config_path = repo / CONFIG_NAME
    script = expected_script(repo)

    if not script.is_file():
        raise SystemExit(f"ERROR: MCP server not found: {script}")
    if not example_path.is_file():
        raise SystemExit(f"ERROR: template not found: {example_path}")

    example = load_jsonc(example_path)
    existing = load_jsonc(config_path)
    wanted = script.as_posix()

    if args.check:
        found = current_script_path(existing)
        if found is None:
            print(f"missing or unconfigured {CONFIG_NAME} -- run: python scripts/setup_mcp.py")
            return 1
        if Path(found).as_posix() != wanted:
            print(f"stale {CONFIG_NAME}: academic-search -> {found}")
            print(f"expected: {wanted}")
            print("run: python scripts/setup_mcp.py")
            return 1
        print(f"OK: {CONFIG_NAME} academic-search -> {found}")
        return 0

    config = build_config(repo, example, existing)
    config_path.write_text(HEADER + json.dumps(config, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {config_path}")
    print(f"  academic-search -> {wanted}")
    others = sorted(k for k in config["mcp"] if k != "academic-search")
    if others:
        print(f"  preserved: {', '.join(others)}")
    print(f"  ({CONFIG_NAME} is gitignored; commit {EXAMPLE_NAME} instead)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())