#!/usr/bin/env python3
"""setup_mcp.py — configure the MCP servers for OpenCode and for Claude Code.

Two targets, one template (`opencode.jsonc.example`):

- **OpenCode** (default): write the machine-local `opencode.jsonc`.
- **Claude Code** (`--claude`): register the same servers with `claude mcp`, so
  `gdrive` and `academic-search` exist in Claude Code sessions as well. See
  "Claude Code" below.

OpenCode part
-------------

OpenCode resolves a *relative* MCP `cwd` against the **session directory**, not
against the config file or the git root. A repo-relative `cwd` therefore works
only while you happen to sit at the repository root and breaks as soon as a
session is rooted anywhere else (`papers/<slug>/`, a legacy folder, a subagent
directory):

    NotFound: FileSystem.access (D:\\...\\papers\\c20-2026\\.agents\\skills\\...)

The academic-search server does not need a `cwd` at all: it imports
`sources`/`utils` as plain top-level modules (Python puts the script's own
directory on `sys.path[0]`) and loads `config.toml` through `Path(__file__)`.
So this script drops `cwd` entirely and writes an **absolute script path**
resolved from the repository root. That works from any subdirectory, on any
platform, on any machine.

`opencode.jsonc` holds an absolute path, so it is machine-local and gitignored;
`opencode.jsonc.example` is the committed template. Every clone runs this once:

    python scripts/setup_mcp.py

Servers already present in `opencode.jsonc` (for example `gdrive`) are
preserved: this script only owns the entries declared in the example.

Claude Code part
----------------
`opencode.jsonc` means nothing to Claude Code, which keeps its servers in
`~/.claude.json` (or `$CLAUDE_CONFIG_DIR/.claude.json`). `--claude` translates each
`local` server of the template into a stdio spec and registers it with
`claude mcp add-json`:

- `__REPO_ROOT__` becomes the absolute repository path, as for OpenCode.
- `{env:NAME}` placeholders are filled from the process environment, then from the
  gitignored `.env` at the repository root. Values are never printed; a placeholder
  with no value is reported and left out rather than passed through literally.
- On Windows a command that resolves to a `.cmd`/`.bat` shim (`pnpm`, `npx`) is
  wrapped in `cmd /c`, which Claude Code needs to spawn it; real executables (`uv`)
  are not.
- The default scope is `local` (this project, this machine, stored outside the
  repository). `user` makes the servers available in every project. `project` is
  deliberately not offered: it writes `.mcp.json` into the repository, and the
  environment values (Drive folder ids) must not be committed.
- It is idempotent: a server already registered with the same spec is left alone,
  a stale one is replaced, a missing one is added.

A running Claude Code process never picks up a server registered after it started.
Conversations run as background sessions in a daemon, and `claude --resume <id>` only
re-attaches to one that is still alive, so `/exit` does not restart it: run
`claude respawn <session-id>` (then `claude attach <session-id>`). The startup
timeouts in the template are OpenCode's and have no per-server equivalent here;
`gdrive` connects in about 3 s, far inside Claude Code's default.

Usage:
    python scripts/setup_mcp.py                        # write/refresh opencode.jsonc
    python scripts/setup_mcp.py --check                # verify only; exit 1 if stale/missing
    python scripts/setup_mcp.py --claude               # register the servers in Claude Code
    python scripts/setup_mcp.py --claude --check       # verify only (reads ~/.claude.json)
    python scripts/setup_mcp.py --claude --only gdrive # a subset of the template's servers
    python scripts/setup_mcp.py --claude --scope user  # every project on this machine
    python scripts/setup_mcp.py --all                  # OpenCode and Claude Code
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _repo import find_repo_root  # noqa: E402

REPO_ROOT_TOKEN = "__REPO_ROOT__"
CONFIG_NAME = "opencode.jsonc"
EXAMPLE_NAME = "opencode.jsonc.example"
DOTENV_NAME = ".env"
ENV_PLACEHOLDER = re.compile(r"\{env:([A-Za-z_][A-Za-z0-9_]*)\}")
CLAUDE_SCOPES = ("local", "user")

HEADER = """// opencode.jsonc — GENERATED by scripts/setup_mcp.py. Do not edit by hand.
//
// This file is machine-local and gitignored because it contains an absolute
// path to the MCP server. To change which servers are configured, edit
// opencode.jsonc.example and re-run:  python scripts/setup_mcp.py
//
// Any MCP server you add by hand is preserved across runs.
"""


def strip_jsonc(text: str) -> str:
    """Remove `//` and block comments and trailing commas, respecting strings."""
    out: list[str] = []
    i, n = 0, len(text)
    in_string = False
    quote = ""
    while i < n:
        ch = text[i]
        if in_string:
            out.append(ch)
            if ch == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                in_string = False
            i += 1
            continue
        if ch in "\"'":
            in_string = True
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(ch)
        i += 1
    return re.sub(r",(\s*[}\]])", r"\1", "".join(out))


def load_jsonc(path: Path) -> dict:
    """Read a JSONC file into a dict; return {} when absent or unreadable."""
    if not path.is_file():
        return {}
    data = json.loads(strip_jsonc(path.read_text(encoding="utf-8")))
    return data if isinstance(data, dict) else {}


def expected_script(repo: Path) -> Path:
    return repo / ".agents" / "skills" / "paper-search" / "mcp-server" / "academic_search_server.py"


def current_script_path(config: dict) -> str | None:
    """Extract the configured server script path from an opencode.jsonc mapping."""
    servers = config.get("mcp")
    if not isinstance(servers, dict):
        return None
    # Tolerate both the flat (V1) and the nested `mcp.servers` (V2) shapes.
    if isinstance(servers.get("servers"), dict):
        servers = servers["servers"]
    entry = servers.get("academic-search")
    if not isinstance(entry, dict):
        return None
    for arg in entry.get("command", []):
        if str(arg).endswith("academic_search_server.py"):
            return str(arg)
    return None


def _split_servers(mcp_dict: dict) -> tuple[dict, dict]:
    """Split an `mcp` mapping into (servers, rest).

    V2 nests servers under `mcp.servers`; V1 placed them directly under `mcp`.
    The flat branch treats any dict value with `type`/`command`/`url` as a
    server and keeps mcp-level keys (e.g. `timeout`) in `rest`.
    """
    if not isinstance(mcp_dict, dict):
        return {}, {}
    if isinstance(mcp_dict.get("servers"), dict):
        return (
            dict(mcp_dict["servers"]),
            {k: v for k, v in mcp_dict.items() if k != "servers"},
        )
    servers: dict = {}
    rest: dict = {}
    for key, value in mcp_dict.items():
        if isinstance(value, dict) and ("type" in value or "command" in value or "url" in value):
            servers[key] = value
        else:
            rest[key] = value
    return servers, rest


def _server_names(config: dict) -> list[str]:
    """Server names regardless of flat (V1) or nested (V2) shape."""
    mcp = (config or {}).get("mcp")
    if not isinstance(mcp, dict):
        return []
    servers, _ = _split_servers(mcp)
    return sorted(servers)


def resolve_example(repo: Path, example: dict) -> dict:
    """The template with `__REPO_ROOT__` replaced by the absolute repository path."""
    return json.loads(json.dumps(example).replace(REPO_ROOT_TOKEN, repo.as_posix()))


def build_config(repo: Path, example: dict, existing: dict) -> dict:
    """Generated example (paths resolved) + any hand-added servers/keys from existing.

    Output is always the V2 shape: `mcp.servers.<name>`. Legacy flat configs
    (`mcp.<name>`) are migrated on write; hand-added servers are preserved.
    """
    resolved = resolve_example(repo, example)
    out: dict = {k: v for k, v in resolved.items() if k != "mcp"}
    resolved_servers, resolved_rest = _split_servers(resolved.get("mcp") or {})
    existing_servers, existing_rest = _split_servers((existing or {}).get("mcp") or {})

    merged_servers: dict = dict(resolved_servers)
    for name, cfg in existing_servers.items():
        merged_servers.setdefault(name, cfg)
    merged_rest: dict = dict(resolved_rest)
    for key, value in existing_rest.items():
        merged_rest.setdefault(key, value)

    for key, value in (existing or {}).items():
        if key != "mcp":
            out.setdefault(key, value)

    out["mcp"] = {**merged_rest, "servers": merged_servers}
    # $schema first, for readability.
    ordered = {"$schema": out.pop("$schema")} if "$schema" in out else {}
    ordered.update(out)
    return ordered


# --- Claude Code -------------------------------------------------------------------

def parse_dotenv(text: str) -> dict[str, str]:
    """Minimal `.env` reader: `KEY=value`, optional `export`, quotes, `#` comments."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        key, sep, value = line.partition("=")
        key = key.strip()
        if not sep or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        else:
            value = re.sub(r"\s+#.*$", "", value)  # an inline comment, only when unquoted
        out[key] = value
    return out


def environment_sources(repo: Path, environ: dict[str, str] | None = None) -> dict[str, str]:
    """Where `{env:NAME}` is looked up: the process environment over the repo `.env`."""
    environ = os.environ if environ is None else environ
    dotenv = repo / DOTENV_NAME
    values = parse_dotenv(dotenv.read_text(encoding="utf-8")) if dotenv.is_file() else {}
    values.update({k: v for k, v in environ.items() if v != ""})
    return values


def resolve_env(env: dict | None, source: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    """Fill `{env:NAME}` placeholders. Returns (resolved, keys left out for lack of a value).

    A placeholder that cannot be filled is left out, never passed on literally: the
    server would otherwise read the text `{env:GDRIVE_FOLDER_ID}` as the folder id.
    """
    resolved: dict[str, str] = {}
    missing: list[str] = []
    for key, template in (env or {}).items():
        template = str(template)
        names = ENV_PLACEHOLDER.findall(template)
        if any(not source.get(n) for n in names):
            missing.append(key)
            continue
        resolved[key] = ENV_PLACEHOLDER.sub(lambda m: source[m.group(1)], template)
    return resolved, missing


def needs_cmd_wrapper(executable: str, platform: str = sys.platform, which=shutil.which) -> bool:
    """True on Windows when `executable` is a `.cmd`/`.bat` shim, which cannot be spawned directly."""
    if platform != "win32":
        return False
    found = which(executable)
    return bool(found) and str(found).lower().endswith((".cmd", ".bat"))


def to_claude_spec(server: dict, source: dict[str, str], platform: str = sys.platform,
                   which=shutil.which) -> tuple[dict, list[str]]:
    """OpenCode `local` server entry -> Claude Code stdio spec, plus env keys left out."""
    command = [str(part) for part in server.get("command") or []]
    if not command:
        raise ValueError("server has no command")
    if needs_cmd_wrapper(command[0], platform, which):
        command = ["cmd", "/c", *command]
    env, missing = resolve_env(server.get("environment"), source)
    spec: dict = {"type": "stdio", "command": command[0], "args": command[1:]}
    if env:
        spec["env"] = env
    return spec, missing


def claude_config_path(environ: dict[str, str] | None = None, home: Path | None = None) -> Path:
    """Where Claude Code keeps user/local MCP servers."""
    environ = os.environ if environ is None else environ
    base = environ.get("CLAUDE_CONFIG_DIR")
    return (Path(base) if base else (home or Path.home())) / ".claude.json"


def _same_path(a: str, b: Path) -> bool:
    norm = lambda p: os.path.normcase(os.path.normpath(str(p)))  # noqa: E731
    return norm(a) == norm(b)


def registered_servers(scope: str, repo: Path, config_path: Path) -> dict[str, dict]:
    """The servers Claude Code has for `scope`, read straight from its config file.

    Reading the file is instant and offline; `claude mcp list` spawns every server to
    health-check it. A `local` entry is keyed by the project path.
    """
    if not config_path.is_file():
        return {}
    data = json.loads(config_path.read_text(encoding="utf-8"))
    if scope == "user":
        return dict(data.get("mcpServers") or {})
    for key, project in (data.get("projects") or {}).items():
        if _same_path(key, repo):
            return dict((project or {}).get("mcpServers") or {})
    return {}


def spec_status(expected: dict, actual: dict | None) -> str:
    """`ok` | `stale` | `missing`, comparing what would be registered with what is."""
    if actual is None:
        return "missing"
    norm = lambda s: {  # noqa: E731
        "type": s.get("type", "stdio"), "command": s.get("command"),
        "args": list(s.get("args") or []), "env": dict(s.get("env") or {})}
    return "ok" if norm(expected) == norm(actual) else "stale"


def _redact(text: str, spec: dict) -> str:
    """Hide the spec's environment values wherever a CLI error might echo them."""
    for value in (spec.get("env") or {}).values():
        if value and len(str(value)) >= 3:
            text = text.replace(str(value), "<hidden>")
    return text


def run_claude(repo: Path, example: dict, *, scope: str = "local", only: list[str] | None = None,
               check: bool = False, config_path: Path | None = None, claude_bin: str | None = None,
               source: dict[str, str] | None = None, runner=subprocess.run,
               platform: str = sys.platform, which=shutil.which, out=print) -> int:
    """Register (or with `check`, verify) the template's local servers in Claude Code."""
    servers, _ = _split_servers(resolve_example(repo, example).get("mcp") or {})
    servers = {n: s for n, s in servers.items() if s.get("type", "local") == "local"}
    if only:
        unknown = [n for n in only if n not in servers]
        if unknown:
            out(f"ERROR: not in {EXAMPLE_NAME}: {', '.join(unknown)} (has: {', '.join(sorted(servers))})")
            return 2
        servers = {n: servers[n] for n in only}
    config_path = config_path or claude_config_path()
    source = environment_sources(repo) if source is None else source
    current = registered_servers(scope, repo, config_path)
    claude_bin = claude_bin or shutil.which("claude")

    failures = 0
    changed: list[str] = []
    for name in sorted(servers):
        spec, missing = to_claude_spec(servers[name], source, platform, which)
        for key in missing:
            out(f"  warning: {name}: {key} has no value in the environment or {DOTENV_NAME}; left out")
        status = spec_status(spec, current.get(name))
        if check:
            out(f"  {name}: {status}  (scope {scope})")
            failures += status != "ok"
            continue
        if status == "ok":
            out(f"  {name}: already registered, unchanged  (scope {scope})")
            continue
        if not claude_bin:
            out("ERROR: the `claude` CLI is not on PATH; install Claude Code, or use --check")
            return 1
        if status == "stale":
            runner([claude_bin, "mcp", "remove", name, "--scope", scope], cwd=str(repo),
                   capture_output=True, text=True)
        proc = runner([claude_bin, "mcp", "add-json", name, json.dumps(spec), "--scope", scope],
                      cwd=str(repo), capture_output=True, text=True)
        if proc.returncode != 0:
            detail = _redact((proc.stderr or proc.stdout or "").strip(), spec)
            out(f"  {name}: FAILED to register: {detail}")
            failures += 1
            continue
        out(f"  {name}: {'replaced' if status == 'stale' else 'registered'}  (scope {scope})")
        changed.append(name)

    if check and failures:
        out("run: python scripts/setup_mcp.py --claude" + (f" --scope {scope}" if scope != "local" else ""))
    if changed:
        out("Registered servers load when a Claude Code session starts. A conversation already "
            "running will not see them:")
        out("relaunch it: `claude respawn <session-id>`, then `claude attach <session-id>` "
            "(`/exit` and `claude --resume` only re-attach to the live process).")
    return 1 if failures else 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Configure the MCP servers for OpenCode (opencode.jsonc) and Claude Code."
    )
    ap.add_argument("--root", default=None, help="repository root (auto-detected)")
    ap.add_argument("--check", action="store_true",
                    help="report a missing/stale configuration and exit 1 without changing anything")
    ap.add_argument("--claude", action="store_true",
                    help="register the template's servers in Claude Code instead of writing opencode.jsonc")
    ap.add_argument("--all", action="store_true", help="configure OpenCode and Claude Code")
    ap.add_argument("--scope", choices=CLAUDE_SCOPES, default="local",
                    help="Claude Code scope: local (this project; default) or user (every project)")
    ap.add_argument("--only", nargs="+", metavar="NAME",
                    help="Claude Code: register only these servers of the template")
    args = ap.parse_args()

    repo = Path(args.root).resolve() if args.root else find_repo_root()
    example_path = repo / EXAMPLE_NAME
    config_path = repo / CONFIG_NAME
    script = expected_script(repo)

    if not script.is_file():
        raise SystemExit(f"ERROR: MCP server not found: {script}")
    if not example_path.is_file():
        raise SystemExit(f"ERROR: template not found: {example_path}")

    example = load_jsonc(example_path)
    do_claude = args.claude or args.all
    if do_claude:
        label = "check" if args.check else "register"
        print(f"Claude Code ({label}, scope {args.scope}):")
        code = run_claude(repo, example, scope=args.scope, only=args.only, check=args.check)
        if not args.all or code:
            return code
        print()
    existing = load_jsonc(config_path)
    wanted = script.as_posix()

    if args.check:
        found = current_script_path(existing)
        if found is None:
            print(f"missing or unconfigured {CONFIG_NAME} -- run: python scripts/setup_mcp.py")
            return 1
        if Path(found).as_posix() != wanted:
            print(f"stale {CONFIG_NAME}: academic-search -> {found}")
            print(f"expected: {wanted}")
            print("run: python scripts/setup_mcp.py")
            return 1
        print(f"OK: {CONFIG_NAME} academic-search -> {found}")
        return 0

    config = build_config(repo, example, existing)
    config_path.write_text(HEADER + json.dumps(config, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {config_path}")
    print(f"  academic-search -> {wanted}")
    others = [k for k in _server_names(config) if k != "academic-search"]
    if others:
        print(f"  preserved: {', '.join(others)}")
    print(f"  ({CONFIG_NAME} is gitignored; commit {EXAMPLE_NAME} instead)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())